### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by ameryllis** [Drakansoul/DisPlace#3]
Hello there! I had the previous version installed and when I tried to update, I received an error, so I first closed and reopened my game, then I went and removed the plugin and reinstalled it. Now, trying to install the plugin, I am receiving the same error.

Installer Error
Failed to install Plugin DisPlace Plugin.
Please restart your game and try again. If this error occurs again, please contact the plugin author.

**Comment by YsEmei** [comment]
You could ask in [Puni.sh](https://puni.sh/) Discord's **#plugin-developent** channel. They even have a pinned video guide on how to find new memory addresses. Ask around in there.
https://discord.gg/Zzrcc8kmvy
